### ISSUE TITLE
Разработка дизайна и верстка всплывающего окна

### ISSUE THREAD

**Issue by Tiikara** [Tiikara/TeacherHelper#7]
Разработка дизайна и верстка всплывающего окна для подтверждения действий пользователя.

_js/confirm.js_ - html код блока
_css/modal.css_ - таблицы стилей

> Выполнить до 29.03.2015

**Comment by DashaOgienko** [comment]
тиран! деспот!

**Comment by Tiikara** [comment]
Выполнено [Commit #56e977](https://github.com/Tiikara/TeacherHelper/commit/56e9778a97512f0525adc79fc5f283529179e33c)
